# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  chat-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: List files in the root directory
      run: ls -al
    - name: List files in chat-service directory
      run: ls -al chat-service
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
      working-directory: ./chat-service
    - name: Build Project
      run: cd chat-service && npm run build --if-present
    - name: Run Tests
      run: cd chat-service && npm test

  notification-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: List files in the root directory
      run: ls -al
    - name: List files in notification-service directory
      run: ls -al notification-service
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        cache: 'npm'
    - name: Install Dependencies
      run: cd notification-service && npm ci
    - name: Build Project
      run: cd notification-service && npm run build --if-present
    - name: Run Tests
      run: cd notification-service && npm test

  user-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: List files in the root directory
      run: ls -al
    - name: List files in user-service directory
      run: ls -al user-service
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        cache: 'npm'
    - name: Install Dependencies
      run: cd user-service && npm ci
    - name: Build Project
      run: cd user-service && npm run build --if-present
    - name: Run Tests
      run: cd user-service && npm test

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: List files in the root directory
      run: ls -al
    - name: List files in frontend directory
      run: ls -al frontend
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        cache: 'npm'
    - name: Install Dependencies
      run: cd frontend && npm ci
    - name: Run Tests
      run: cd frontend && npm test
    - name: Build Project
      run: cd frontend && npm run build
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/build
